# Generated by Django 5.2.17 on 2026-08-16 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=50)),
                ('purpose', models.CharField(choices=[('Sale', 'For Sale'), ('Rent', 'For Rent'), ('Installments', 'Installments Plan')], max_length=20)),
                ('city', models.CharField(default='Karachi', max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('exact_address', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('price', models.BigIntegerField()),
                ('advance', models.BigIntegerField(blank=True, null=True)),
                ('area_size', models.PositiveIntegerField()),
                ('area_unit', models.CharField(default='Sq. Yds', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('furnishing', models.CharField(blank=True, max_length=30)),
                ('facing', models.CharField(blank=True, max_length=30)),
                ('condition', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('owner_contact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold')], default='Active', max_length=10)),
                ('sale_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sale_feedback', models.TextField(blank=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_phone', models.CharField(max_length=20)),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='properties.property')),
            ],
            options={
                'ordering': ['-contacted_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/%Y/%m/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
